### ISSUE TITLE
android studio 2.3.2 for mac 不能使用

### ISSUE THREAD

**Issue by chenjia1992** [JessYanCoding/ArmsComponent-Template#1]
把NewArmsComponent文件夹复制到/Applications/Android Studio.app/Contents/plugins/android/lib/templates/gradle-projects 文件夹目录下, 重启android studio创建module无效, 而且就连创建普通的android library也不会成功了

**Comment by JessYanCoding** [comment]
我已在 README 作出说明了的, 本模板只保证绝对能兼容最新的 AndroidStudio 稳定版, 由于精力原因其他版本暂不做保证, 目前的最新稳定版是 v3.1.2
