### ISSUE TITLE
大神有没有关于模板开发的文档

### ISSUE THREAD

**Issue by seen2016** [JessYanCoding/ArmsComponent-Template#3]
请教一下大神，我也学习一下这个模板开发，大神帮推荐一下这方面的文档！谢谢了

**Comment by JessYanCoding** [comment]
百度一下 FreeMarker 关键词，文章挺多的，张鸿洋也写过，可以搜搜，过段时间我也会用文章总结一下 AS 的几种模板用法，毕竟我一路走来，模板也用了很久，不过关于 Module 的模板教程应该没有，这是我原创的，但都是用的 FreeMarker 语言，区别不大，只是一些细节的区别

**Comment by seen2016** [comment]
近一段日子有些忙，好久没上github了，没看到大神的回复，真是抱歉！谢谢大神的指点，我已大至了解了！真的非常感谢

**Comment by JessYanCoding** [comment]
我公众号最新一篇文章就讲的是模板，你有兴趣的话，可以搜索微信公众号 [JessYan]
