### ISSUE TITLE
大佬还在吗？新建的项目加入模板后新建module一直报错

### ISSUE THREAD

**Issue by NingJinBo** [JessYanCoding/ArmsComponent-Template#4]
错误信息如下:Could not read script 'C:\workspace\MvparmsDemo\common_component_build.gradle' as it does not exist.这个咋解决啊？尝试了几种方式都不行，不过在您原来的项目基础上新建没有报错

**Comment by JessYanCoding** [comment]
兄弟，报错已经说的很明白了，让你把 https://github.com/JessYanCoding/ArmsComponent/blob/master/common_component_build.gradle  这个文件复制到你本地
