### ISSUE TITLE
在AS3.6版本上插件失效

### ISSUE THREAD

**Issue by eleveno** [JessYanCoding/ArmsComponent-Template#5]
新建module没有创建arms module选项

**Comment by JessYanCoding** [comment]
升级删除了，自己重新装一遍插件

**Comment by eleveno** [comment]
已经重新复制了，但是没有这个选项，MAPArms全家桶是正常的

**Comment by JessYanCoding** [comment]
兼容了，你下载最新代码就可以了，现在新建 module  的时候就可以选择 MAPArms全家桶 生成第一个页面
